SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS STUDENTMATERIALS;
DROP TABLE IF EXISTS COURSEMATERIALS;
DROP TABLE IF EXISTS ENROLLMENTS;
DROP TABLE IF EXISTS RESOURCES;
DROP TABLE IF EXISTS OPENCOURSES;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS STAFFS;
DROP TABLE IF EXISTS DEPARTMENTS;